# Generated by Django 2.1.2 on 2018-11-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181030_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ('-id',)},
        ),
    ]
