# Generated by Django 2.1.2 on 2018-11-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181124_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsbanner',
            old_name='inage_url',
            new_name='image_url',
        ),
    ]
